### PR TITLE
Bump zxcvbn-php version

### PR DESCRIPTION
**Pull request by bubenkoff**
This change is [Reviewable](https://reviewable.io/reviews/olssonm/l5-zxcvbn/3)

### CODE REVIEW

**Comment by olssonm** [comment]
Great – thanks! Released a new version on packagist (2.1) also which includes this update: https://packagist.org/packages/olssonm/l5-zxcvbn#v2.1 

Just out of curiosity – are you using this package in a project? Just fun to know =)

**Comment by bubenkoff** [comment]
thanks!
yes we do use it at https://hugo.events/ for website and backoffice
for website we've decided to lower threshold to 0 for now as it was too hard for people to come up with initial passwords :)

**Comment by olssonm** [comment]
Cool, I see – thanks for sharing! =) Always fun to how people use different packages. Nifty service you got there too.

**Comment by bubenkoff** [comment]
thanks for this work!

**Pull request merged**
