### PR TITLE
Update for PHP 8

### PR DESCRIPTION
**Pull request by olssonm**

### CODE REVIEW

**Comment by wreality** [comment]
Sorry to dredge an old pull request up, but was the change back to bjeavons/zxcvbn-php due to PHP 8 incompatibility?

Was investigating this as I'm trying to get the laravel validator to match the javascript library's result. (no demands, no complaints, just trying to understand to help figure out how I'm going to solve my dilemma. 😄 )

**Comment by olssonm** [comment]
@wreality mkopinsky/zxcvbn-php was a fork of bjeavons/zxcvbn-php which made some great improvements. It was later discontinued and merged back into bjeavons/zxcvbn-php.

As the former hadn't been updated for ~2 years I made the call to switch back to bjeavons/zxcvbn-php as the positive changes made in mkopinsky/zxcvbn-php is included anyway.

But you're saying that there are som compatibility issues? Is this with the Dropbox zxcvbn-library? Feel free to open an issue and I'll happily take a look at it 🙂

**Comment by wreality** [comment]
Ok, that makes a lot of sense.  I didn't realize that bjeavons/zxcvbn-php had since incorporated mkopinsky/zxcvbn-php to have better parity with the javascript library now.  I'll do some more testing and develop some examples that illustrate the discrepancies I'm seeing. (I think it's mainly around multi-byte encoding differences).  Thank you!

**Comment by olssonm** [comment]
@wreality Please do! Yeah, I was late to the party there too. 

If there suddenly are discrepancies between Dropbox's Zxcvn and bjeavons/zxcvbn-php (and there weren't any in mkopinsky/zxcvbn-php) my guess would be that there's a bug in zxcvbn-php, their dictionary isn't up to date or the like.

**Pull request merged**
